// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MuxiKeStack/be-feed/events"
	"github.com/MuxiKeStack/be-feed/grpc"
	"github.com/MuxiKeStack/be-feed/ioc"
	"github.com/MuxiKeStack/be-feed/repository"
	"github.com/MuxiKeStack/be-feed/repository/dao"
	"github.com/MuxiKeStack/be-feed/service"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	feedPushEventDAO := dao.NewGORMFeedPushEventDAO(db)
	feedEventRepository := repository.NewFeedEventRepository(feedPushEventDAO)
	feedService := service.NewFeedService(feedEventRepository)
	feedServiceServer := grpc.NewFeedServiceServer(feedService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(feedServiceServer, client, logger)
	saramaClient := ioc.InitKafka()
	feedEventConsumer := events.NewFeedEventConsumer(saramaClient, logger, feedService)
	v := ioc.InitConsumers(feedEventConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}
